#!/usr/bin/env python3
"""Pick deterministic dev/holdout splits per domain and write runs/SPLITS.md.

Holdout tasks are scored once at the end of the day and never tuned on.
Selection is by md5 of the task name, so it is reproducible, order-independent
and not biased by task naming or dataset order. Re-running never changes an
existing split unless --force is passed.

Usage:
    python scripts/make_splits.py            # all domains found in hackathon.toml
    python scripts/make_splits.py --force    # regenerate (only before any tuning!)
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def holdout_size(n: int) -> int:
    if n <= 10:
        return max(2, n // 3)  # tiny training set: keep dev usable
    return min(8, max(5, n // 4))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--force", action="store_true", help="overwrite an existing SPLITS.md")
    args = ap.parse_args()

    out = REPO / "runs" / "SPLITS.md"
    if out.exists() and not args.force:
        sys.exit(f"{out} already exists; refusing to change a recorded split (use --force only "
                 "if no tuning has happened yet)")

    cfg = tomllib.loads((REPO / "hackathon.toml").read_text(encoding="utf-8"))
    default_dir = cfg.get("data", {}).get("local_dir", "dataset/hackathon")
    lines = ["# Dev / holdout splits", "",
             "Holdout = scored once at end of day, never tuned on. Dev = iterate freely.",
             "Split rule: sort tasks by `md5(task_name)`, first K are holdout "
             "(K = n//4 clamped to [5, 8]; smaller for tiny sets). Generated by scripts/make_splits.py.", ""]

    for name, dom in sorted((cfg.get("domains") or {}).items()):
        task_dir = REPO / dom.get("dataset_dir", f"{default_dir}/{name}/tasks")
        if not task_dir.is_dir():
            print(f"WARNING: {name}: no task dir at {task_dir} — skipped (data not pulled?)", file=sys.stderr)
            continue
        # same filter as skilltrainbench.config.task_names
        tasks = sorted(d.name for d in task_dir.iterdir()
                       if d.is_dir() and not d.is_symlink() and (d / "task.toml").is_file())
        if not tasks:
            print(f"WARNING: {name}: task dir empty — skipped", file=sys.stderr)
            continue
        k = holdout_size(len(tasks))
        ranked = sorted(tasks, key=lambda t: hashlib.md5(t.encode()).hexdigest())
        holdout, dev = sorted(ranked[:k]), sorted(ranked[k:])
        lines += [f"## {name} — {len(tasks)} training tasks: {len(dev)} dev / {len(holdout)} holdout", "",
                  f"Holdout ({len(holdout)}):", *[f"- {t}" for t in holdout], "",
                  f"Dev ({len(dev)}):", *[f"- {t}" for t in dev], "",
                  "Holdout as --tasks arg:", "```", ",".join(holdout), "```", "",
                  "Dev as --tasks arg:", "```", ",".join(dev), "```", ""]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
